### ISSUE TITLE
How to get power production?

### ISSUE THREAD

**Issue by MrNorth35** [tibbercom/Tibber.SDK.NET#1]
I am testing this awesome SDK out, and it seems to be working fine for most things. One thing I can't access is the power production at our home. There is support for production in the TIbber API, but everything is either null or 0. I tried to access the API directly and I get empty values there as well. The documentation is very poor, so it is impossible to find out exactly what values Tibber are providing here?

I assumed that once you register a solar panel system in Tibber (we have SolarEdge), it is added as a power production device, and the values collected should be the ones the API provide, but that is not the case it seems? Do you know how to access this data? I could access the data through SolarEdge REST, but I am limited to 200 queries/day, which is not enough. It would be best to access everything through the Tibber subscription API, since thye seem to get data more often.

Also, the signalStrength value is also null, for some reason. We have a Watty at home, and it is definetely working, so I guess this is also not working/not implemented.

**Comment by Husqvik** [comment]
`powerProduction` is net production that you deliver back to grid and comes from Pulse/Watty. It's not gross production your inverter provides. Right now other device data than Pulse/Watty is not exposed through the API.

`signalStrength` is populated only at the time we receive it from Pulse/Watty. For watty it's once per minute I believe. When we receive it the next record in the stream will contain the value, then all the next `null` again until we receive new value. It's like that to avoid misleading we have fresh signal value with every reading.

**Comment by kr0815** [comment]
I have the same Problem:

`{
  viewer {
    homes {
      production(resolution: DAILY, last: 2) {
        nodes {
          from
          to
          production
          productionUnit
        }
      }
    }
  }
}
`

This works with the Demo Token, but not with my own Token?

Answer with Demo Token:

`{
  "data": {
    "viewer": {
      "homes": [
        {
          "production": {
            "nodes": [
              {
                "from": "2023-05-05T00:00:00.000+02:00",
                "to": "2023-05-06T00:00:00.000+02:00",
                "production": 16.718,
                "productionUnit": "kWh"
              },
              {
                "from": "2023-05-06T00:00:00.000+02:00",
                "to": "2023-05-07T00:00:00.000+02:00",
                "production": 26.807,
                "productionUnit": "kWh"
              }
            ]
          }
        }
      ]
    }
  }
}`


Answer with my Token:

`{
  "data": {
    "viewer": {
      "homes": [
        {
          "production": {
            "nodes": []
          }
        }
      ]
    }
  }
}`

**Comment by toini** [comment]
@kr0815 did you have production exceeding consumption during that time? Note the answer above:

`powerProduction` is net production that you deliver back to grid and comes from Pulse/Watty. It's not gross production your inverter provides.

**Comment by kr0815** [comment]
yes, i had exceeding power that left the house
This is also shown in the App

If i do a query with "production" i get an empty result

if i try "powerProduction" - this word is unknown / not even suggested

In other forums - same problem, no answer

**Comment by toini** [comment]
@kr0815 we need to take a look at your data. Would you share your email address you used to register to Tibber here or send it to me at toni@tibber.com?

**Comment by kr0815** [comment]
> @kr0815 we need to take a look at your data. Would you share your email address you used to register to Tibber here or send it to me at [toni@tibber.com](mailto:toni@tibber.com)?

Hi Toni,

i send you a mail - would be really cool if we could solve it

**Comment by DerMarshal** [comment]
Hello @toini,

is there a solution to this issue?
I am facing the same behavior, no production values available.
(Testing in https://developer.tibber.com/explorer)

I noticed, when generating the access token, "Consumption" is listed as a selectable value, but "production" is not.

![image](https://github.com/tibber/Tibber.SDK.NET/assets/47794286/7e59e82a-22c6-4269-8a0b-3d5ac4022016)

Thank you.

**Comment by toini** [comment]
@DerMarshal the previous request was directed to support@tibber.com as the issue is not with the .NET client but rather with the API. Could you contact them?

**Comment by DerMarshal** [comment]
@toini  Thanks for the info, I will contact support@tibber.com.

**Comment by kr0815** [comment]
> @DerMarshal 

for your information, after many mails, my problem was never solved - so i used another energy meter 7 made my own calculation to get the feeded power

**Comment by toini** [comment]
@kr0815 @DerMarshal can you confirm you both see/saw production in the Tibber mobile app but not in API?
